sisjuridico/apps/expediente/urls.py
from django.conf.urls import patterns, url, include

urlpatterns = patterns('apps.expediente.views',

	#este es mi primer index
    url(r'^registro_expediente/$', 'registro_expediente'),
    url(r'^actualizar_expediente/$', 'actualizar_expediente'),
    url(r'^eliminar_expediente/$', 'eliminar_expediente'),
    url(r'^busq_ajax_exp/$', 'busq_ajax_exp'),
    

    #categoria
    url(r'^registro_categoria/$', 'registro_categoria'),
    url(r'^actualizar_categoria/$', 'actualizar_categoria'),
    url(r'^eliminar_categoria/$', 'eliminar_categoria'),
    url(r'^busq_ajax_ct/$', 'busq_ajax_ct'),

    #hoja de envio
    url(r'^registro_hoja_envio/$', 'registro_hoja_envio'),
    url(r'^actualizar_hoja_envio/$', 'actualizar_hoja_envio'),
    url(r'^eliminar_hoja_envio/$', 'eliminar_hoja_envio'),

    #resolucion
    url(r'^registro_resolucion/$', 'registro_resolucion'),
    url(r'^actualizar_resolucion/$', 'actualizar_resolucion'),
    url(r'^eliminar_resolucion/$', 'eliminar_resolucion'),
    url(r'^busq_ajax_re/$', 'busq_ajax_re'),
    




	)

sisjuridico/sisjuridico/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = [ 
    # Examples:
    # url(r'^$', 'clase1.views.home', name='home'),
    url(r'^media/(?P<path>.*)$','django.views.static.serve', {'document_root': settings.MEDIA_ROOT, }),
    url(r'^', include('apps.busqueda.urls')),
    url(r'^', include('apps.expediente.urls')),
    url(r'^', include('apps.matenimiento.urls')),
    url(r'^', include('apps.reportes.urls')),
    url(r'^', include('apps.seguridad.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

sisjuridico/apps/expediente/models.py
from django.db import models
from apps.matenimiento.models import accion, oficina

class categoria(models.Model):
    descripcion = models.CharField(max_length=100)

class resolucion(models.Model):
    numero    = models.CharField(max_length=20)
    contenido = models.FileField(upload_to='Resolucion/%Y/%m/%d')


class expedientes(models.Model):
    nro              = models.CharField(max_length=20)
    fecha            = models.DateField()
    fecha_expediente = models.DateField()
    asunto           = models.TextField()
    contenido        = models.FileField(upload_to='Expediente/%Y/%m/%d')
    idcategoria      = models.ForeignKey(categoria)
    idresolucion     = models.ManyToManyField(resolucion) 
    estado           = models.TextField()   

class hojaEnvio(models.Model):
    idaccion      = models.ForeignKey(accion)
    idoficina     = models.ForeignKey(oficina)
    asunto        = models.TextField()
    observaciones = models.TextField()
    fecha_emision   = models.DateField()
    fecha_recepcion = models.DateField()
    documento_adjun = models.FileField(upload_to='HojaEnvio/%Y/%m/%d')
    num_follos      = models.IntegerField()
    idexpediente    = models.ForeignKey(expedientes)

sisjuridico/apps/expediente/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.db.models import Max, Q
from apps.seguridad.models import permisos
from apps.reportes.models import historial
from .forms import formCategoria, formExpediente, formHojadeEnvio, formResolucion, formExpedienteA, formHojadeEnvioU,formResolucionA
from .models import categoria, expedientes, hojaEnvio, accion, oficina, resolucion
from apps.paginacion import paginacion
import datetime, time
today  = datetime.datetime.now()
fecha  = today.strftime("%Y-%m-%d")
hora   = time.strftime("%H:%M:%S") 

# Crea tus vista aqui.
def historiales(request,mod):
    ip        = request.META['REMOTE_ADDR']
    equipo    = request.META['HTTP_USER_AGENT']
    a = historial()
    a.idusuario_id  = request.user.id
    a.fecha         = fecha
    a.hora          = hora
    a.equipo        = equipo
    a.ip            = ip 
    a.modulo        = mod[0]
    a.accion        = mod[1]
    a.idaccion      = mod[2]
    a.save()


def permi(request,url):
    idp = request.user.idperfil_id
    mod = permisos.objects.filter(idmodulo__url=url, idperfil_id=idp).values('idmodulo__url','buscar','eliminar','editar','insertar','imprimir','ver')
    return mod

@login_required(login_url='/')
def registro_expediente(request):
    estado =  permi(request, "registro_expediente")
    listaCategoria = [{'id':con.id,'descripcion':con.descripcion} for con in categoria.objects.all()]
    listaResolucion = [{'id':con.id,'numero':con.numero} for con in resolucion.objects.all()]

    #print(request.POST)
    if request.method == 'POST': 
        idd = request.POST.get("id","")
        if idd == "undefined":
            idc = 1
            formu = formExpediente(request.POST,request.FILES )
            if formu.is_valid():
                formu.save()
                idp = expedientes.objects.latest('id')
                historiales(request,["expediente","registrar",idp.id])
            else:
                return render(request,'expediente/expediente/form_exp.html',{'formu':formu})
        else:
            idc = request.POST.get("idc","")
        
        expediente = expedientes.objects.filter(idcategoria= idc).order_by('-id')  
        return render(request,'expediente/expediente/ajax_expediente.html',{'lista':expediente,'n':'expedienteU','estado':estado})            
    else:
        idc= 1
        expediente = expedientes.objects.filter(idcategoria= idc).order_by('-id')
        formu = formExpediente()
        modulo = {'formu':formu, 'url':'registro_expediente/','n':'expedienteU','estado':estado,'idcategoria':listaCategoria, 'idresolucion':listaResolucion}
        return paginacion(request,expediente, modulo, 'expediente/expediente/expediente.html' )        

@login_required(login_url='/')
def actualizar_expediente(request):
    expediente = expedientes.objects.all().order_by('-id')
    estado =  permi(request, "registro_expediente")
    if request.method == 'POST': 
        idp = request.POST.get("id","")
        a=get_object_or_404(expedientes,pk=idp)
        form=formExpedienteA(request.POST, request.FILES, instance=a)
        if form.is_valid():
            form.save()       
            historiales(request,["expediente","actualizar",idp])
            return render(request,'expediente/expediente/ajax_expediente.html',{'lista':expediente,'n':'expedienteU','estado':estado}) 
        else:
            return render(request,'expediente/expediente/form_exp.html',{'formu':form})             
    else:
        idp = request.GET.get("id","")
        a=get_object_or_404(expedientes,pk=idp)
        form= formExpedienteA(instance=a)
        return render(request,'expediente/expediente/modal.html',{'formu':form,'url':'actualizar_expediente/','n':'expedienteU','u':'expedienteU','estado':estado})  


@login_required(login_url='/')
def eliminar_expediente(request):
    expediente = expedientes.objects.all().order_by('-id')
    estado =  permi(request, "registro_expediente")
    if request.method == 'GET' and request.is_ajax(): 
        idb = request.GET.get("id","")
        get_object_or_404(expedientes,pk=idb).delete()
        historiales(request,["expediente","eliminar",idb])
        return render(request,'expediente/expediente/ajax_expediente.html',{'lista':expediente,'n':'expedienteU','estado':estado})     

def busq_ajax_exp(request):
    dat = request.GET.get('datos')
    estado =  permi(request, "registro_expediente")
    e = expedientes.objects.filter( Q(nro__contains=dat))[:10]
    modulo = {'lista':e,'n':'expedienteU','estado':estado}
    return render(request,'expediente/expediente/ajax_expediente.html', modulo)

@login_required(login_url='/')
def registro_hoja_envio(request):
    
    estado =  permi(request, "registro_hoja_envio")
    listaAccion = [{'id':con.id,'accion':con.accion} for con in accion.objects.all()]
    listaOficina = [{'id':con.id,'oficina':con.oficina} for con in oficina.objects.all()]
    listaExpediente = [{'id':con.id,'nro': con.nro} for con in expedientes.objects.all()]

    if request.method == 'POST': 
        idd = request.POST.get("id","")
        if idd == "undefined":
            idc = 1
            formH = formHojadeEnvio(request.POST,request.FILES )
            if formH.is_valid():
                formH.save()
                idp = hojaEnvio.objects.latest('id')                                
                historiales(request,["hojaEnvio","registrar",idp.id])
            else:
                return render(request,'expediente/hoja_envio/form_hoj.html',{'formuH':formH})                
        else:
            idc = request.POST.get("idc","")  

        hojaEnvios = hojaEnvio.objects.values('id','idaccion__accion','idoficina__oficina','asunto','observaciones','fecha_emision','fecha_recepcion','documento_adjun','num_follos').filter(idexpediente=idc).order_by('id')            
        return render(request,'expediente/hoja_envio/ajax_hoja_envio.html',{'lista':hojaEnvios,'n':'hoja_envioU','estado':estado})            
    else:
        idc = 1
        hojaEnvios = hojaEnvio.objects.values('id','idaccion__accion','idoficina__oficina','asunto','observaciones','fecha_emision','fecha_recepcion','documento_adjun','num_follos').filter(idexpediente=idc).order_by('id')            
        formH = formHojadeEnvio()
        modulo = {'formuH':formH,'url':'registro_hoja_envio/','n':'hoja_envioU','estado':estado,'idaccion':listaAccion,'idoficina':listaOficina,'idexpediente':listaExpediente}
        return paginacion(request,hojaEnvios, modulo, 'expediente/hoja_envio/hoja_envio.html' )        

@login_required(login_url='/')
def actualizar_hoja_envio(request):
    hojaEnvios = hojaEnvio.objects.values('id','idaccion__accion','idoficina__oficina','asunto','observaciones','fecha_emision','fecha_recepcion','documento_adjun','num_follos').order_by('id')
    estado =  permi(request, "registro_hoja_envio")
    if request.method == 'POST' and request.is_ajax(): 
        idp = request.POST.get("id","")
        a=get_object_or_404(hojaEnvio,pk=idp)
        form=formHojadeEnvioU(request.POST, instance=a)
        if form.is_valid():
            form.save()
            historiales(request,["hojaEnvio","actualizar",idp])
            return render(request,'expediente/hoja_envio/ajax_hoja_envio.html',{'lista':hojaEnvios,'n':'hoja_envioU','estado':estado})            
        else:
            return render(request,'expediente/hoja_envio/form_hoj.html',{'formuH':form})            
        
        
    else:
        idp = request.GET.get("id","")
        a=get_object_or_404(hojaEnvio,pk=idp)
        form= formHojadeEnvioU(instance=a)
        return render(request,'expediente/hoja_envio/modal.html',{'formuH':form,'url':'actualizar_hoja_envio/','n':'hoja_envioU','u':'hoja_envioU','estado':estado})  

@login_required(login_url='/')
def eliminar_hoja_envio(request):
    hojaEnvios = hojaEnvio.objects.all().order_by('id')
    estado =  permi(request, "registro_hoja_envio")
    if request.method == 'GET' and request.is_ajax(): 
        idb = request.GET.get("id","")
        get_object_or_404(hojaEnvio,pk=idb).delete()
        historiales(request,["hojaEnvio","eliminar",idb])
        return render(request,'expediente/hoja_envio/ajax_hoja_envio.html',{'lista':hojaEnvios,'n':'hoja_envioU','estado':estado})     



@login_required(login_url='/')
def registro_resolucion(request):

    resoluciones = resolucion.objects.all().order_by('-id')
    estado =  permi(request, "registro_resolucion")

    if request.method == 'POST': 
        formH = formResolucion(request.POST,request.FILES )
        #print (formH)
        if formH.is_valid():
            formH.save()
            idp = resolucion.objects.latest('id')
            historiales(request,["resolucion","registrar",idp.id])
            return render(request,'expediente/resolucion/ajax_resolucion.html',{'lista':resoluciones,'n':'resolucionU','estado':estado})            
        else:
            return render(request,'expediente/resolucion/form_re.html',{'formuH':formH})                        
        
    else:
        formH = formResolucion()
        modulo = {'formuH':formH,'url':'registro_resolucion/','n':'resolucionU','estado':estado}
        return paginacion(request,resoluciones, modulo, 'expediente/resolucion/resolucion.html' )

@login_required(login_url='/')
def actualizar_resolucion(request):
    resoluciones = resolucion.objects.all().order_by('-id')
    estado =  permi(request, "registro_resolucion")
    if request.method == 'POST': 
        idp = request.POST.get("id","")
        a=get_object_or_404(resolucion,pk=idp)
        form=formResolucionA(request.POST, request.FILES, instance=a)
        if form.is_valid():
            form.save()
            historiales(request,["resolucion","actualizar",idp])

sisjuridico/apps/expediente/templates/expediente/expediente/ajax_expediente.html
{% for p in lista %}
  <tr>
    <th>{{forloop.counter}}</th>
    <td>{{p.nro}}</td>
    <td>{{p.asunto}}</td>
    <td>{{p.fecha}}</td>
    <td>{{p.fecha_expediente}}</td>
    <td>
    <a href="media/{{p.contenido}}" target="_blank">ver</a>
    </td>
    <td>
    <ol>
    {% for a in p.idresolucion.all  %}
        <li>{{a.numero}} → <a href="media/{{a.contenido}}" target="_blank">ver</a></li>
    {% endfor %}
    </ol>
    </td>
    <td>{{p.estado}}</td>      
    {% for i in  estado %}
    {% if i.editar == 1 %}
    <td>
      <a href="#">
        <i onclick="actualizar({{p.id}},'actualizar_expediente','{{n}}')" class="fa fa-pencil-square-o fa-2x"></i>
      </a>
    </td>
    {% endif %}

    {% if i.eliminar == 1 %}
    <td>
      <a onclick="eliminar({{p.id}},'eliminar_expediente','{{n}}')" href="#eliminar">
      <i style="color: red" class="fa fa-trash-o  fa-2x"></i>
      </a>
    </td>
    {% endif %}
  {% endfor %}
  </tr>
{% endfor %}

sisjuridico/apps/expediente/templates/expediente/expediente/expediente.html
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
    <br>
        <ol class="breadcrumb">
            <li>
                <a href="/">Home</a>
            </li>
            <li class="active">
                <strong>Registro de Expedientes</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2"></div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title form-inline">
                    
                    {% for i in  estado %}
                    <div class="col-md-1">
                    {% if i.insertar == 1 %}
                      <button data-toggle="modal" data-target="#Modal"class="btn btn-sm btn-primary" type="submit"><strong>Nuevo</strong></button>
                    {% endif %}
                    </div>
                    <div class="col-md-3">
                    {% if i.buscar == 1 %}
                    <input type="search" placeholder="Buscar" class="form-control Bex">
                    {% endif %}
                    </div>
                    
                    <div class="col-md-4">
                    <select class="form-control selEx chosen-select" >
                      {% for c in  idcategoria %}
                        <option value="{{c.id}}"
                        {% if c.id == 1  %}
                                selected="selected"
                        {% endif %} >{{c.descripcion}}</option>
                      {% endfor %}
                    </select>  
                    </div>
                    <input class="form-control" onblur="nroPag(this,'{{url}}')" style="width:70px" type="number" id="selP" value="{{pag}}"> 
                </div>
                <div class="ibox-content table-responsive">
                     <h3 align="center">EXPEDIENTES</h3>    

                     <table class="table table-bordered" style="  margin-bottom: -5px;">
                          <thead>
                              <tr>
                                
                                  <th>#</th>
                                  <th>Número</th>
                                  <th>Asunto</th>
                                  <th>Fecha</th>
                                  <th>Fecha de Expediente</th>
                                  <th>Contenido</th>
                                  <th>Resolucion</th>
                                  <th>Estado</th>
                                  {% if i.editar == 1 %}
                                  <th>Editar</th>
                                  {% endif %}
                                  {% if i.eliminar == 1 %}
                                    <th>Eliminar</th>
                                  {% endif %}
                                {% endfor %}
                              </tr>
                          </thead>
                          <tbody class="{{n}}">
                            {% include "expediente/expediente/ajax_expediente.html" %}
                          </tbody>
                      </table> 
                      {% with lista as paginacion  %}
                          {% include "paginacion.html" %}
                      {% endwith %}
                </div>
            </div>
        </div>
    </div>
</div>
<div class="modalP"></div>


{% with nombre=formu n=p u=n%}
<div id="Modal{{n}}" class="modal fade" aria-hidden="true">
    
    <div class="modal-dialog">
    
        <div class="modal-content">
            <div class="modal-body">
                <h5>Formulario <small>llenar todos los campos</small></h5>

                
                    <div class="ibox-content">
                        <div class="row">
                            <form method="post" enctype="multipart/form-data" id="formulario{{n}}">
                            {% csrf_token %}
                            <div class="col-sm-6 b-r"><h3 class="m-t-none m-b">Expedientes</h3>
                                <label for="id_asunto">Categoría:</label>
                                <select name="idcategoria" class="form-control chosen-select" id="id_idcategoria" >
                                {% for c in  idcategoria %}
                                    <option value="{{c.id}}">{{c.descripcion}}</option>
                                {% endfor %}
                                </select>                            
                                <label for="id_nro">Nro de Expediente:</label>
                                {{formu.nro}}
                                <label for="id_fecha">Fecha:</label>
                                {{formu.fecha}}
                                <label for="id_fecha_expediente">Fecha de Expediente:</label>
                                {{formu.fecha_expediente}}
                                <label for="id_asunto">Asunto:</label>
                                {{formu.asunto}}


                            </div>
                            <div class="col-sm-6"><h4>Subir Expediente</h4>
                                <label for="id_asunto">Expediente:</label>
                                {{formu.contenido}}
                                <br>
                                <label for="id_resolucion">Resolucion:</label>
                                <br>
                                <select data-placeholder="resolucion..." name="idresolucion" multiple class="form-control chosen-select" id="id_idresolucion" >
                                {% for c in  idresolucion %}
                                    <option value="{{c.id}}">{{forloop.counter}} → <strong>{{c.numero}} </strong> </option>
                                {% endfor %}
                                </select>   
                                
                                <label for="estado">Estado:</label>
                                {{formu.estado}}                            
                            </div>

                            </form> 
                        </div>
                    </div>
        </div>


            <div class="modal-footer">
                <input class="btn btn-sm btn-primary" onclick="guardarF('{{url}}','{{n}}','{{u}}')"  type="button" value= "guardar"/>
                <button type="button" class="btn btn-sm  btn-danger" data-dismiss="modal"> Cancelar</button>
            </div>
            

        </div>

    </div>
</div>
{% endwith %}

            
{% load static from  staticfiles %}
<script src="{%static 'js/base.js' %}"></script>
<script src="{%static 'js/expediente.js' %}"></script>
           

sisjuridico/apps/expediente/templates/expediente/expediente/form_exp.html
{% csrf_token %}
<div class="col-sm-6 b-r"><h3 class="m-t-none m-b">Expedientes</h3>
    <label for="id_asunto" 
    {% if formu.idcategoria.errors %}
    data-html="true" data-toggle="popover" data-content="
        <p style='color:red; font-size: 13px; margin: 0 0 0px;'> este campo es obligatorio </p>
    "
    {% endif %}
    >Categoría:</label>
    {{formu.idcategoria.errors}}
    {{formu.idcategoria}}                                                           
    <label for="id_nro" 
    {% if formu.nro.errors %}
    data-html="true" data-toggle="popover" data-content="
        <p style='color:red; font-size: 13px; margin: 0 0 0px;'> este campo es obligatorio </p>
    "
    {% endif %}
    >Nro de Expediente:</label>
    {{formu.nro.errors}}
    {{formu.nro}}
    <label for="id_fecha" 
    {% if formu.fecha.errors %}
    data-html="true" data-toggle="popover" data-content="
        <p style='color:red; font-size: 13px; margin: 0 0 0px;'> este campo es obligatorio </p>
    
    "
    {% endif %}
    >Fecha:</label>
    {{formu.fecha.errors}}
    {{formu.fecha}}
    <label for="id_fecha_expediente"
    {% if formu.fecha_expediente.errors %}
    data-html="true" data-toggle="popover" data-content="
        <p style='color:red; font-size: 13px; margin: 0 0 0px;'> este campo es obligatorio </p>
    
    "
    {% endif %}
    >Fecha de Expediente:</label>
    {{formu.fecha_expediente.errors}}
    {{formu.fecha_expediente}}
    <label for="id_asunto" 
    {% if formu.asunto.errors %}
    data-html="true" data-toggle="popover" data-content="
        <p style='color:red; font-size: 13px; margin: 0 0 0px;'> este campo es obligatorio </p>
    
    "
    {% endif %}
    >Asunto:</label>
    {{ formu.asunto.errors }}
    {{formu.asunto}}

</div>
<div class="col-sm-6"><h4>Subir Expediente</h4>
    <label for="id_asunto" 
    {% if formu.contenido.errors %}
    data-html="true" data-toggle="popover" data-content="
        <p style='color:red; font-size: 13px; margin: 0 0 0px;'> este campo es obligatorio </p>
    "
    {% endif %}
    >Expediente:</label>
    {{formu.contenido.errors}}
    {{formu.contenido}}
    <br>
    <label for="id_resolucion" 
    {% if formu.idresolucion.errors %}
    data-html="true" data-toggle="popover" data-content="
        <p style='color:red; font-size: 13px; margin: 0 0 0px;'> este campo es obligatorio </p>
    "
    {% endif %}
    >Resolucion:</label>
    {{formu.idresolucion.errors}}
    {{formu.idresolucion}}  
                                           
    <label for="estado" 
    {% if formu.estado.errors %}
    data-html="true" data-toggle="popover" 
    data-content="    
        <p style='color:red; font-size: 13px; margin: 0 0 0px;'> este campo es obligatorio </p>
    "
    {% endif %}
    >Estado:</label>
    {{formu.estado.errors}}
    {{formu.estado}}                            
</div>

sisjuridico/apps/expediente/templates/expediente/expediente/modal.html
<div id="Modal{{n}}" class="modal fade" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body">
                <form method="post" id="formulario{{n}}" enctype="multipart/form-data">
                {% csrf_token %}

                <div class="col-sm-6 b-r"><h3 class="m-t-none m-b">Expedientes</h3>
                    <label for="id_asunto">Categoría:</label>
                    {{formu.idcategoria}}                                                           
                    <label for="id_nro">Nro de Expediente:</label>
                    {{formu.nro}}
                    <label for="id_fecha">Fecha:</label>
                    {{formu.fecha}}
                    <label for="id_fecha_expediente">Fecha de Expediente:</label>
                    {{formu.fecha_expediente}}
                    <label for="id_asunto">Asunto:</label>
                    {{formu.asunto}}

                </div>
                <div class="col-sm-6"><h4>Subir Expediente</h4>
                    <label for="id_asunto">Expediente:</label>
                    {{formu.contenido}}
                    <br>
                    <label for="id_resolucion">Resolucion:</label>
                    <br>
                    {{formu.idresolucion}}  
                                            
                    <label for="estado">Estado:</label>
                    {{formu.estado}}                            
                    </div>

                 </form> 

                
            </div>
            <div class="modal-footer">
                <button class="btn btn-sm btn-primary guar" onclick="guardarF('{{url}}','{{n}}','{{u}}')" type="button">guardar</button>
                <button type="button" class="btn btn-sm  btn-danger" data-dismiss="modal"> Cancelar</button>
            </div>
        </div>

    </div>
</div>